version: "3.8"
networks:
  tugas4law:
services:
  nginx:
    build: ./nginx/
    ports:
      - 80:80
    networks:
      - tugas4law
    depends_on:
      - read
      - update

  read:
    build:
      context: ./read/
      target: Production
    ports:
      - 5002:5002
    restart: always
    depends_on:
      - db
    networks:
      - tugas4law

  update:
    build:
      context: ./update/
      target: Production
    ports:
      - 5001:5001
    restart: always
    depends_on:
      - db
    networks:
      - tugas4law

  db:
    image: postgres:13.3-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: law
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tugas4law
    ports:
      - 5432:5432
    networks:
      - tugas4law

volumes:
  db-data:
    driver: local
